all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /home/ec2-user/Confluent.pem
    security_mode: tls
preflight:
  hosts:
    172.31.85.62:
    172.31.89.138:
    172.31.89.86:
    172.31.90.200:
zookeeper:
  hosts:
    172.31.85.62:
    172.31.89.138:
    172.31.89.86:
broker:
  hosts:
    172.31.85.62:
      kafka:
        broker:
          id: 1
    172.31.89.138:
      kafka:
        broker:
          id: 2
    172.31.89.86:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    172.31.90.200:
control-center:
  hosts:
    172.31.90.200:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 172.31.90.200:8083
connect-distributed:
  hosts:
    172.31.90.200:
kafka-rest:
  hosts:
    172.31.90.200:
ksql:
  hosts:
    172.31.90.200:
tools:
  hosts:
    172.31.85.62:
