all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /home/ec2-user/Confluent.pem
    security_mode: tls
preflight:
  hosts:
    172.31.86.241:
    172.31.89.232:
    172.31.91.110:
    172.31.94.252:
zookeeper:
  hosts:
    172.31.86.241:
    172.31.89.232:
    172.31.91.110:
broker:
  hosts:
    172.31.86.241:
      kafka:
        broker:
          id: 1
    172.31.89.232:
      kafka:
        broker:
          id: 2
    172.31.91.110:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    172.31.94.252:
control-center:
  hosts:
    172.31.94.252:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 172.31.94.252:8083
connect-distributed:
  hosts:
    172.31.94.252:
kafka-rest:
  hosts:
    172.31.94.252:
ksql:
  hosts:
    172.31.94.252:
tools:
  hosts:
    172.31.86.241:
